/*----- PROTECTED REGION ID(Pet7019Class.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Pet7019Class.cpp
//
// description : C++ source for the Pet7019Class.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Pet7019 once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Pet7019Class.h>

/*----- PROTECTED REGION END -----*/	//	Pet7019Class.cpp

//-------------------------------------------------------------------
/**
 *	Create Pet7019Class singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Pet7019_class(const char *name) {
		return Pet7019_ns::Pet7019Class::init(name);
	}
}

namespace Pet7019_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
Pet7019Class *Pet7019Class::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		Pet7019Class::Pet7019Class(string &s)
 * description : 	constructor for the Pet7019Class
 *
 * @param s	The class name
 */
//--------------------------------------------------------
Pet7019Class::Pet7019Class(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering Pet7019Class constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(Pet7019Class::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::constructor

	cout2 << "Leaving Pet7019Class constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		Pet7019Class::~Pet7019Class()
 * description : 	destructor for the Pet7019Class
 */
//--------------------------------------------------------
Pet7019Class::~Pet7019Class()
{
	/*----- PROTECTED REGION ID(Pet7019Class::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		Pet7019Class::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
Pet7019Class *Pet7019Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new Pet7019Class(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		Pet7019Class::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
Pet7019Class *Pet7019Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		rebootClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *rebootClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "rebootClass::execute(): arrived" << endl;
	((static_cast<Pet7019 *>(device))->reboot());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		pingClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *pingClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "pingClass::execute(): arrived" << endl;
	((static_cast<Pet7019 *>(device))->ping());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum Pet7019Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum Pet7019Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum Pet7019Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void Pet7019Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "ModuleID";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ModuleIP";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ModulePort";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void Pet7019Class::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void Pet7019Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(Pet7019Class::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Pet7019(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Pet7019 *dev = static_cast<Pet7019 *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(Pet7019Class::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void Pet7019Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(Pet7019Class::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::attribute_factory_before
	//	Attribute : calibrationAI
	calibrationAIAttrib	*calibrationai = new calibrationAIAttrib();
	Tango::UserDefaultAttrProp	calibrationai_prop;
	//	description	not set for calibrationAI
	//	label	not set for calibrationAI
	//	unit	not set for calibrationAI
	//	standard_unit	not set for calibrationAI
	//	display_unit	not set for calibrationAI
	//	format	not set for calibrationAI
	//	max_value	not set for calibrationAI
	//	min_value	not set for calibrationAI
	//	max_alarm	not set for calibrationAI
	//	min_alarm	not set for calibrationAI
	//	max_warning	not set for calibrationAI
	//	min_warning	not set for calibrationAI
	//	delta_t	not set for calibrationAI
	//	delta_val	not set for calibrationAI
	
	calibrationai->set_default_properties(calibrationai_prop);
	//	Not Polled
	calibrationai->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(calibrationai);

	//	Attribute : numberChannelDO
	numberChannelDOAttrib	*numberchanneldo = new numberChannelDOAttrib();
	Tango::UserDefaultAttrProp	numberchanneldo_prop;
	//	description	not set for numberChannelDO
	//	label	not set for numberChannelDO
	//	unit	not set for numberChannelDO
	//	standard_unit	not set for numberChannelDO
	//	display_unit	not set for numberChannelDO
	//	format	not set for numberChannelDO
	//	max_value	not set for numberChannelDO
	//	min_value	not set for numberChannelDO
	//	max_alarm	not set for numberChannelDO
	//	min_alarm	not set for numberChannelDO
	//	max_warning	not set for numberChannelDO
	//	min_warning	not set for numberChannelDO
	//	delta_t	not set for numberChannelDO
	//	delta_val	not set for numberChannelDO
	
	numberchanneldo->set_default_properties(numberchanneldo_prop);
	//	Not Polled
	numberchanneldo->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(numberchanneldo);

	//	Attribute : numberChannelAI
	numberChannelAIAttrib	*numberchannelai = new numberChannelAIAttrib();
	Tango::UserDefaultAttrProp	numberchannelai_prop;
	//	description	not set for numberChannelAI
	//	label	not set for numberChannelAI
	//	unit	not set for numberChannelAI
	//	standard_unit	not set for numberChannelAI
	//	display_unit	not set for numberChannelAI
	//	format	not set for numberChannelAI
	//	max_value	not set for numberChannelAI
	//	min_value	not set for numberChannelAI
	//	max_alarm	not set for numberChannelAI
	//	min_alarm	not set for numberChannelAI
	//	max_warning	not set for numberChannelAI
	//	min_warning	not set for numberChannelAI
	//	delta_t	not set for numberChannelAI
	//	delta_val	not set for numberChannelAI
	
	numberchannelai->set_default_properties(numberchannelai_prop);
	//	Not Polled
	numberchannelai->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(numberchannelai);

	//	Attribute : modelName
	modelNameAttrib	*modelname = new modelNameAttrib();
	Tango::UserDefaultAttrProp	modelname_prop;
	//	description	not set for modelName
	//	label	not set for modelName
	//	unit	not set for modelName
	//	standard_unit	not set for modelName
	//	display_unit	not set for modelName
	//	format	not set for modelName
	//	max_value	not set for modelName
	//	min_value	not set for modelName
	//	max_alarm	not set for modelName
	//	min_alarm	not set for modelName
	//	max_warning	not set for modelName
	//	min_warning	not set for modelName
	//	delta_t	not set for modelName
	//	delta_val	not set for modelName
	
	modelname->set_default_properties(modelname_prop);
	//	Not Polled
	modelname->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(modelname);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(Pet7019Class::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void Pet7019Class::pipe_factory()
{
	/*----- PROTECTED REGION ID(Pet7019Class::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::pipe_factory_before
	/*----- PROTECTED REGION ID(Pet7019Class::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void Pet7019Class::command_factory()
{
	/*----- PROTECTED REGION ID(Pet7019Class::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::command_factory_before


	//	Command reboot
	rebootClass	*prebootCmd =
		new rebootClass("reboot",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(prebootCmd);

	//	Command ping
	pingClass	*ppingCmd =
		new pingClass("ping",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	ppingCmd->set_polling_period(5000);
	command_list.push_back(ppingCmd);

	/*----- PROTECTED REGION ID(Pet7019Class::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		Pet7019Class::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void Pet7019Class::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(Pet7019Class::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		Pet7019Class::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void Pet7019Class::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Pet7019 *dev = static_cast<Pet7019 *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(Pet7019Class::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pet7019Class::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : Pet7019Class::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *Pet7019Class::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(Pet7019Class::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	Pet7019Class::Additional Methods
} //	namespace
